# Generated by Django 2.0.4 on 2018-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiNumber', models.CharField(max_length=1)),
                ('audiNoseats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmName', models.CharField(max_length=200)),
                ('filmYear', models.CharField(max_length=4)),
                ('filmDirector', models.CharField(max_length=50)),
                ('filmCountry', models.CharField(max_length=50)),
                ('filmActors', models.CharField(max_length=200)),
                ('filmPlot', models.CharField(max_length=500)),
            ],
        ),
    ]
