# Generated by Django 2.0.4 on 2018-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imgdir',
            field=models.CharField(default='reservation/img', max_length=100),
            preserve_default=False,
        ),
    ]
