# Generated by Django 2.0.4 on 2018-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20180509_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
