# Generated by Django 2.0.4 on 2018-05-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_film_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='CreditCard',
        ),
    ]
