# Generated by Django 2.0.4 on 2018-06-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_screening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audi',
            old_name='audiNoseats',
            new_name='audiNoSeats',
        ),
        migrations.AddField(
            model_name='audi',
            name='audiRows',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
