# Generated by Django 2.0.4 on 2018-06-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20180601_1645'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='screening',
            unique_together={('audi', 'date_time')},
        ),
    ]
