# Generated by Django 2.0.4 on 2018-06-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20180608_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Screening')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatPos', models.CharField(max_length=3)),
                ('Status', models.CharField(choices=[('AVL', 'Available'), ('BLK', 'Blocked'), ('RSV', 'Reserved')], default='AVL', max_length=15)),
                ('Screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Screening')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='booking',
            name='seatPos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Seat'),
        ),
    ]
